### ISSUE TITLE
TypeError: Cannot read property 'components' of undefined

### ISSUE THREAD

**Issue by sebikovacs** [FortechRomania/react-redux-complete-example#11]
Any ideea why this might be happening?
```
TypeError: Cannot read property 'components' of undefined
    at prefetchDataForComponents (/home/sebi/test/reservr-dashboard/src/server/index.js:45:22)
    at /home/sebi/test/reservr-dashboard/src/server/index.js:29:9
    at /home/sebi/test/reservr-dashboard/node_modules/react-router/lib/match.js:67:5
    at /home/sebi/test/reservr-dashboard/node_modules/react-router/lib/createTransitionManager.js:63:11
    at next (/home/sebi/test/reservr-dashboard/node_modules/react-router/lib/AsyncUtils.js:52:7)
    at loopAsync (/home/sebi/test/reservr-dashboard/node_modules/react-router/lib/AsyncUtils.js:56:3)
    at matchRoutes (/home/sebi/test/reservr-dashboard/node_modules/react-router/lib/matchRoutes.js:253:29)
    at Object.match (/home/sebi/test/reservr-dashboard/node_modules/react-router/lib/createTransitionManager.js:57:33)
    at match (/home/sebi/test/reservr-dashboard/node_modules/react-router/lib/match.js:56:21)
    at /home/sebi/test/reservr-dashboard/src/server/index.js:28:5

```

**Comment by alexnm** [comment]
how do you pass renderProps the the prefetchData function? problem must be from there

**Comment by sebikovacs** [comment]
@alexnm I haven't touched the codebase. It's the default behaviour. The example app works it just throws this error in my console. BTW I'm using ubuntu.

**Comment by alexnm** [comment]
which url are you accessing? the main page?

**Comment by sebikovacs** [comment]
it's the same for all urls

**Comment by alexnm** [comment]
Can't say what the problem is, for some reason `renderProps` is undefined in your case. it works for me
